### ISSUE TITLE
program does not work

### ISSUE THREAD

**Issue by lnxbil** [kennylevinsen/gocnc#12]
Hejsan!

I cross-compiled it on my Mac to run on the Raspberry Pi 1 B+ and I can interact with my GRBL with `screen` and `minicom`. I can even send my minimal working example to the GRBL manually via

```
root@laser-engraver:~# cat test.ngc > /dev/ttyUSB0
```

but if I want to try out your program, it just displays stuff and it then hangs (or even it seems, it does not move my laser engraver), but this is printed:

```
root@laser-engraver:~# timeout 60 ./gocnc --device=/dev/ttyUSB0 --baudrate=115200 --stdout --autostart --stats --opt test.ngc
Metrics
-------------------------
   Moves: 7
   Feedrates (mm/min): 250
   ETA: 9s
   X (mm): 0 <-> 10
   Y (mm): 0 <-> 10
   Z (mm): 0 <-> 0
-------------------------
(Exported by gocnc)
G21G90

M3S1
F250
G0
G1Y10
X10
Y0
X0
M5
```

I also tried a bunch of other command line parameters including `--no-opt`, yet I cannot get it to work. 
My "unoptimized" input data is as follows:

```
root@laser-engraver:~# cat test.ngc
F250

M3 S1

G0 X0 Y0

G1
Y10
X10
Y0
X0

M5
```

Any ideas?

Många hälsningar från Tyskland
Andreas

**Comment by lnxbil** [comment]
I just set it up with my Mac and it does work there without any problems:

```
MyMac $ ./gocnc --device=/dev/tty.usbserial-A9MPDBFZ --autostart test.ngc
Metrics
-------------------------
   Moves: 7
   Feedrates (mm/min): 250
   ETA: 9s
   X (mm): 0 <-> 10
   Y (mm): 0 <-> 10
   Z (mm): 0 <-> 0
-------------------------
Grbl version 1.1f initialized
 7 / 7 [===================================================] 100.00% 11s
```

**Comment by kennylevinsen** [comment]
Halløjsa!

I suspect the problem is the serial connection hanging. If you try without autostart, it should ask if you want to run the code. If it hangs without making a progress bar after that, then it is the serial connection establishment that hangs (which is either an open() or a bunch of termios stuff).

I haven't played with this project in a while (my CNC is gathering dust :( ). It uses an old fork of goserial I made in 2014 because I was having some issues on Mac. Maybe try using the upstream project?

To do so, change all instances of:

```go
import "github.com/joushou/goserial"
```

with

```go
import "github.com/tarm/goserial"
```

Tell me if it still doesn't work.

Best regards,
Kenny Levinsen

**Comment by lnxbil** [comment]
Yes, that was the right idea. It's working now :-D (It's also working on MacOS with the new version)

Thank you very much

**Comment by lnxbil** [comment]
I still don't know why the default on GitHub is to create pull-requests to your own repository ....

**Comment by lnxbil** [comment]
Something is still very strange. I have to reset the serial device after each run.
